
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Image dinerName;

	private global::Gtk.Label menu;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button soupButton;

	private global::Gtk.Button chefButton;

	private global::Gtk.Button fishButton;

	private global::Gtk.VBox vbox4;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label soupName;

	private global::Gtk.Label specialName;

	private global::Gtk.Label fishName;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Image soup;

	private global::Gtk.Image special;

	private global::Gtk.Image fish;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label soupPrice;

	private global::Gtk.Label specialPrice;

	private global::Gtk.Label fishPrice;

	private global::Gtk.Button exitButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.dinerName = new global::Gtk.Image();
		this.dinerName.Name = "dinerName";
		this.dinerName.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("BAUTISTA_HW1_Diner.dinerName.png");
		this.vbox2.Add(this.dinerName);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.dinerName]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.menu = new global::Gtk.Label();
		this.menu.Name = "menu";
		this.menu.LabelProp = global::Mono.Unix.Catalog.GetString("Menu");
		this.vbox2.Add(this.menu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menu]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.soupButton = new global::Gtk.Button();
		this.soupButton.CanFocus = true;
		this.soupButton.Name = "soupButton";
		this.soupButton.UseUnderline = true;
		this.soupButton.Label = global::Mono.Unix.Catalog.GetString("Today's Soup");
		this.hbox1.Add(this.soupButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.soupButton]));
		w3.Position = 0;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.chefButton = new global::Gtk.Button();
		this.chefButton.CanFocus = true;
		this.chefButton.Name = "chefButton";
		this.chefButton.UseUnderline = true;
		this.chefButton.Label = global::Mono.Unix.Catalog.GetString("Chef's Special");
		this.hbox1.Add(this.chefButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.chefButton]));
		w4.Position = 1;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fishButton = new global::Gtk.Button();
		this.fishButton.CanFocus = true;
		this.fishButton.Name = "fishButton";
		this.fishButton.UseUnderline = true;
		this.fishButton.Label = global::Mono.Unix.Catalog.GetString("Daily Fish");
		this.hbox1.Add(this.fishButton);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fishButton]));
		w5.Position = 2;
		w5.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.soupName = new global::Gtk.Label();
		this.soupName.Name = "soupName";
		this.soupName.LabelProp = global::Mono.Unix.Catalog.GetString("<span font='20' weight='bold' color='white' font-family='courier' background='dark red'>Taco Soup</span>");
		this.soupName.UseMarkup = true;
		this.soupName.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add(this.soupName);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.soupName]));
		w8.Position = 0;
		w8.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.specialName = new global::Gtk.Label();
		this.specialName.Name = "specialName";
		this.specialName.LabelProp = global::Mono.Unix.Catalog.GetString("<span font='20' weight='bold' color='white' font-family='courier' background='dark red'>Teriyaki Chicken</span>");
		this.specialName.UseMarkup = true;
		this.specialName.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add(this.specialName);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.specialName]));
		w9.Position = 1;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fishName = new global::Gtk.Label();
		this.fishName.Name = "fishName";
		this.fishName.LabelProp = global::Mono.Unix.Catalog.GetString("<span font='20' weight='bold' color='white' font-family='courier' background='dark red'>Fried Salmon</span>");
		this.fishName.UseMarkup = true;
		this.fishName.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add(this.fishName);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fishName]));
		w10.Position = 2;
		w10.Fill = false;
		this.vbox4.Add(this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.soup = new global::Gtk.Image();
		this.soup.Name = "soup";
		this.soup.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("BAUTISTA_HW1_Diner.small_square_picture.jpg");
		this.hbox3.Add(this.soup);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.soup]));
		w12.Position = 0;
		w12.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.special = new global::Gtk.Image();
		this.special.Name = "special";
		this.special.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("BAUTISTA_HW1_Diner.sacramento-6th-annual-food-film-festiv-38.jpeg");
		this.hbox3.Add(this.special);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.special]));
		w13.Position = 1;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.fish = new global::Gtk.Image();
		this.fish.Name = "fish";
		this.fish.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("BAUTISTA_HW1_Diner.small_square_picture-2.jpg");
		this.hbox3.Add(this.fish);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.fish]));
		w14.Position = 2;
		this.vbox4.Add(this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.soupPrice = new global::Gtk.Label();
		this.soupPrice.Name = "soupPrice";
		this.soupPrice.LabelProp = global::Mono.Unix.Catalog.GetString("<span font='25' weight='bold' color='white' font-family='papyrus' background='dark red'>$8.99</span>");
		this.soupPrice.UseMarkup = true;
		this.hbox4.Add(this.soupPrice);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.soupPrice]));
		w16.Position = 0;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.specialPrice = new global::Gtk.Label();
		this.specialPrice.Name = "specialPrice";
		this.specialPrice.LabelProp = global::Mono.Unix.Catalog.GetString("<span font='25' weight='bold' color='white' font-family='papyrus' background='dark red'>$12.99</span>");
		this.specialPrice.UseMarkup = true;
		this.hbox4.Add(this.specialPrice);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.specialPrice]));
		w17.Position = 1;
		w17.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fishPrice = new global::Gtk.Label();
		this.fishPrice.Name = "fishPrice";
		this.fishPrice.LabelProp = global::Mono.Unix.Catalog.GetString("<span font='25' weight='bold' color='white' font-family='papyrus' background='dark red'>$10.99</span>");
		this.fishPrice.UseMarkup = true;
		this.hbox4.Add(this.fishPrice);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.fishPrice]));
		w18.Position = 2;
		w18.Fill = false;
		this.vbox4.Add(this.hbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox1.Add(this.vbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox4]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.exitButton = new global::Gtk.Button();
		this.exitButton.CanFocus = true;
		this.exitButton.Name = "exitButton";
		this.exitButton.UseUnderline = true;
		this.exitButton.Label = global::Mono.Unix.Catalog.GetString("Exit");
		this.vbox1.Add(this.exitButton);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.exitButton]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 966;
		this.DefaultHeight = 569;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.soupButton.Clicked += new global::System.EventHandler(this.OnSoupButtonClicked);
		this.chefButton.Clicked += new global::System.EventHandler(this.OnChefButtonClicked);
		this.fishButton.Clicked += new global::System.EventHandler(this.OnFishButtonClicked);
		this.exitButton.Clicked += new global::System.EventHandler(this.OnExitButtonClicked);
	}
}
